#!/bin/bash
set -o errexit

# Only run in the configure phase of the Debian package.
[[ "$1" != "configure" ]] && exit 0

apt-key add /opt/winterman/etc/apt/public.key

systemctl daemon-reload

hostnamectl set-hostname winterman

enabled_units=(
  "ssh.service"
  "winterman-autossh@canyon.service"
  "winterman-apt.timer"
  "winterman-apt.service"
  "ddclient.service"
)

currently_enabled_units="$(systemctl list-unit-files --state=enabled)"
for unit in "${enabled_units[@]}"; do
  [[ "${currently_enabled_units}" == *"${unit}"* ]] && continue
  systemctl enable "${unit}"
  systemctl start "${unit}"
done

exit 0
