#!/bin/bash
set -o errexit

# Only run in the configure phase of the Debian package.
[[ "$1" != "configure" ]] && exit 0

systemctl daemon-reload

hostnamectl set-hostname winterman

enabled_units=(
  "ssh.service"
  "winterman-autossh@canyon.service"
  "winterman-apt.timer"
  "winterman-apt.service"
  "ddclient.service"
)

currently_enabled_units="$(systemctl list-unit-files --state=enabled)"
for unit in "${enabled_units[@]}"; do
  [[ "${currently_enabled_units}" == *"${unit}"* ]] && continue
  systemctl enable "${unit}"
  systemctl start "${unit}"
done


pip_packages=(
  "deepspeech"
)

for package in "${pip_packages[@]}"; do
  pip3 install "${package}" --upgrade
done


exit 0
